/** Browse categories — matched against title, description, skills, company. */

export const CATEGORY_ICON_KEYS = [
  "hotel",
  "teacher",
  "driver",
  "tech",
  "bank",
  "health",
  "sales",
  "hr",
  "marketing",
  "construction",
  "factory",
  "office",
  "guard",
  "support",
  "beauty",
  "farm",
  "cleaning",
  "warehouse",
  "engineering",
  "design",
  "media",
  "government",
  "realestate",
  "labor",
] as const;

export type CategoryIconKey = (typeof CATEGORY_ICON_KEYS)[number];

export const JOB_CATEGORIES = [
  {
    id: "hotel-hospitality",
    name: "Hotel & Restaurant",
    icon: "hotel" as const,
    keywords: [
      "hotel",
      "restaurant",
      "hospitality",
      "waiter",
      "waitress",
      "barista",
      "bartender",
      "chef",
      "cook",
      "kitchen",
      "cafe",
      "resort",
      "lodging",
      "food service",
      "steward",
      "housekeeping hotel",
    ],
  },
  {
    id: "teaching-education",
    name: "Teaching & Education",
    icon: "teacher" as const,
    keywords: [
      "teacher",
      "teaching",
      "tutor",
      "education",
      "school",
      "principal",
      "lecturer",
      "instructor",
      "professor",
      "montessori",
      "training",
      "faculty",
    ],
  },
  {
    id: "driver-delivery",
    name: "Driver & Delivery",
    icon: "driver" as const,
    keywords: [
      "driver",
      "driving",
      "delivery",
      "rider",
      "chauffeur",
      "truck",
      "van driver",
      "bike rider",
      "courier",
      "transport",
      "logistics driver",
    ],
  },
  {
    id: "it-technology",
    name: "IT & Technology",
    icon: "tech" as const,
    keywords: [
      "software",
      "developer",
      "programming",
      "it",
      "tech",
      "engineer",
      "react",
      "javascript",
      "python",
      "full stack",
      "frontend",
      "backend",
      "data",
      "network",
    ],
  },
  {
    id: "bank-finance",
    name: "Bank & Finance",
    icon: "bank" as const,
    keywords: ["bank", "finance", "accounting", "teller", "loan", "insurance", "audit"],
  },
  {
    id: "health-care",
    name: "Health & Care",
    icon: "health" as const,
    keywords: [
      "health",
      "nurse",
      "medical",
      "hospital",
      "pharmacy",
      "care",
      "doctor",
      "clinic",
      "dental",
      "paramedic",
    ],
  },
  {
    id: "sales-retail",
    name: "Sales & Retail",
    icon: "sales" as const,
    keywords: [
      "sales",
      "retail",
      "shop",
      "store",
      "cashier",
      "merchandiser",
      "showroom",
      "business development",
    ],
  },
  {
    id: "hr-recruitment",
    name: "Human Resources",
    icon: "hr" as const,
    keywords: ["human resources", "hr", "recruiter", "talent", "hiring"],
  },
  {
    id: "marketing",
    name: "Marketing & Advertising",
    icon: "marketing" as const,
    keywords: ["marketing", "digital", "seo", "social media", "ads", "brand", "promotion"],
  },
  {
    id: "construction",
    name: "Construction & Civil",
    icon: "construction" as const,
    keywords: [
      "construction",
      "civil",
      "mason",
      "electrician",
      "plumber",
      "carpenter",
      "welder",
      "site",
      "building",
    ],
  },
  {
    id: "manufacturing",
    name: "Factory & Production",
    icon: "factory" as const,
    keywords: [
      "factory",
      "production",
      "manufacturing",
      "operator",
      "assembly",
      "machine",
      "plant",
      "quality control",
    ],
  },
  {
    id: "office-admin",
    name: "Office & Administration",
    icon: "office" as const,
    keywords: [
      "office",
      "admin",
      "administration",
      "receptionist",
      "clerk",
      "secretary",
      "assistant",
      "front desk",
      "data entry",
    ],
  },
  {
    id: "security-guard",
    name: "Security & Guard",
    icon: "guard" as const,
    keywords: ["security guard", "guard", "watchman", "safety officer", "patrol"],
  },
  {
    id: "customer-service",
    name: "Customer Service",
    icon: "support" as const,
    keywords: [
      "customer service",
      "call center",
      "support",
      "helpline",
      "client service",
      "bpo",
    ],
  },
  {
    id: "beauty-wellness",
    name: "Beauty & Salon",
    icon: "beauty" as const,
    keywords: ["beauty", "salon", "spa", "hairdresser", "makeup", "wellness", "barber"],
  },
  {
    id: "agriculture",
    name: "Agriculture & Farming",
    icon: "farm" as const,
    keywords: ["agriculture", "farm", "farming", "livestock", "dairy", "horticulture"],
  },
  {
    id: "housekeeping",
    name: "Housekeeping & Cleaning",
    icon: "cleaning" as const,
    keywords: ["housekeeping", "cleaner", "cleaning", "janitor", "maid", "sanitation"],
  },
  {
    id: "logistics-warehouse",
    name: "Logistics & Warehouse",
    icon: "warehouse" as const,
    keywords: ["warehouse", "logistics", "storekeeper", "inventory", "packing", "supply chain"],
  },
  {
    id: "engineering",
    name: "Engineering",
    icon: "engineering" as const,
    keywords: [
      "engineer",
      "engineering",
      "mechanical",
      "electrical",
      "civil engineer",
      "site engineer",
    ],
  },
  {
    id: "design-creative",
    name: "Design & Creative",
    icon: "design" as const,
    keywords: ["design", "ui", "ux", "graphic", "creative", "figma", "illustrator"],
  },
  {
    id: "content-media",
    name: "Content & Media",
    icon: "media" as const,
    keywords: [
      "content",
      "writing",
      "video",
      "media",
      "journalist",
      "editor",
      "photographer",
      "videographer",
    ],
  },
  {
    id: "government-ngo",
    name: "Government & NGO",
    icon: "government" as const,
    keywords: ["government", "ngo", "public sector", "project officer", "social work"],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    icon: "realestate" as const,
    keywords: ["real estate", "property", "broker", "land", "housing"],
  },
  {
    id: "general-labor",
    name: "General & Skilled Labor",
    icon: "labor" as const,
    keywords: ["labor", "labour", "helper", "technician", "mechanic", "skilled", "worker"],
  },
] as const;

export type JobCategoryId = (typeof JOB_CATEGORIES)[number]["id"];

export function getCategoryById(id: string | undefined) {
  if (!id) return undefined;
  return JOB_CATEGORIES.find((c) => c.id === id);
}

/** Legacy category IDs from older links → current category. */
const LEGACY_CATEGORY_MAP: Record<string, JobCategoryId> = {
  "ui-ux": "design-creative",
  "code-programming": "it-technology",
  bank: "bank-finance",
  health: "health-care",
  writing: "content-media",
  security: "security-guard",
  video: "content-media",
  sales: "sales-retail",
  hr: "hr-recruitment",
};

export function resolveCategoryId(id: string | undefined): JobCategoryId | undefined {
  if (!id) return undefined;
  const direct = getCategoryById(id);
  if (direct) return direct.id;
  return LEGACY_CATEGORY_MAP[id];
}
